language: ruby
rvm:
    - 2.3
script: rspec spec

before_install:
  - sudo apt-get install libtag1-dev

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/202b302701ca7a6ace31
    on_success: always
    on_failure: always
    on_start: false
