---
core:
  prompt: !ruby/string
    str: ! 'cultome> '
    mode: 0
    uncolorized: ! 'cultome> '
    background: 9
  color_palette:
  - :black
  - :red
  - :green
  - :yellow
  - :blue
  - :magenta
  - :cyan
  - :white
  - :light_black
  - :light_red
  - :light_green
  - :light_yellow
  - :light_blue
  - :light_magenta
  - :light_cyan
  - :light_white
basic_command_set:
  seeker_step: 500
copy_to: {}
last_fm:
  similar_results_limit: 10
taste_analizer:
  genres_compatibility:
    ? - Rock
      - Progressive Rock
    : 0.9
    ? - Rock
      - Hard Rock
    : 0.9
    ? - Rock
      - AlternRock
    : 0.9
    ? - Rock
      - Metal
    : 0.7
    ? - Rock
      - Heavy Metal
    : 0.6
    ? - Rock
      - Pop
    : 0.3
    ? - Rock
      - Hip-Hop
    : 0.3
    ? - Rock
      - Alternative
    : 0.2
    ? - Pop
      - BritPop
    : 0.8
    ? - Pop
      - Dance
    : 0.5
    ? - Pop
      - Club
    : 0.5
    ? - Pop
      - Disco
    : 0.4
    ? - Pop
      - Funk
    : 0.2
    ? - BritPop
      - Dance
    : 0.5
    ? - BritPop
      - Club
    : 0.5
    ? - BritPop
      - Disco
    : 0.4
    ? - BritPop
      - Funk
    : 0.2
kill_song: {}
command_aliases:
  aliases:
    exit: quit
    sap: search %1 | play 1
    ls: show @playlist
    p: pause
gesture_analizer: {}
lyric_finder: {}
share_it: {}
