source 'https://rubygems.org'

gem 'activerecord'
gem 'active_support'
gem 'mp3info'
gem 'activerecord-jdbcsqlite3-adapter'
gem 'rb-readline'
gem 'htmlentities'
gem 'json'
gem 'cgi'
gem 'open-uri'
gem 'shellwords'
