user:
  db_adapter: sqlite3
  db_file: ~/.cultome/db.dat
  db_log_file: ~/.cultome/db.log
  file_types: mp3
  config_file: ~/.cultome/config.yml
memory:
  db_adapter: sqlite3
  db_file: /tmp/db.dat
  db_log_file: /tmp/db.log
  file_types: mp3
  config_file: /tmp/config.yml
rspec:
  db_adapter: sqlite3
  db_file: spec/db.dat
  db_log_file: spec/db.log
  file_types: mp3
  config_file: spec/config.yml
