user:
  db_adapter: sqlite3
  db_file: ~/.cultome_new/db.dat
  db_log_file: ~/.cultome_new/db.log
  file_types: mp3
  mplayer_pipe: ~/.cultome_new/mpctr
  config_file: ~/.cultome_new/config.yml
memory:
  db_adapter: sqlite3
  db_file: /tmp/db.dat
  db_log_file: /tmp/db.log
  file_types: mp3
  mplayer_pipe: /tmp/mpctr
  config_file: /tmp/config.yml
rspec:
  db_adapter: sqlite3
  db_file: spec/db.dat
  db_log_file: spec/db.log
  file_types: mp3
  mplayer_pipe: spec/mpctr
  config_file: spec/config.yml
test:
  db_adapter: sqlite3
  db_file: ~/tmp/db.dat
  db_log_file: ~/tmp/db.log
  file_types: mp3
  mplayer_pipe: ~/tmp/mpctr
  config_file: ~/tmp/config.yml
